### ISSUE TITLE
Hi, help me

### ISSUE THREAD

**Issue by FullZero5** [kosmodrey/telebot#1]
/home/ubuntu/workspace/node_modules/telebot/index.js:165
          for (var update of data) {
                          ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/workspace/telebot/server.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by kosmodrey** [comment]
Какая у Вас версия node.js?

**Comment by FullZero5** [comment]
v0.10.35

**Comment by kosmodrey** [comment]
К сожалению эта версия не поддерживает `.. for of ..` из-за этого и возникает данная ошибка. Если возможно, свежую (*v0.12.x*) версию можно установить по этой инструкции https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions

Официальные репозитории *Ubuntu 14.04 LTS* предлагают *Node.js v0.10.x*, думаю стоит сделать патч, чтобы всё шло и на старых версиях. Спасибо за отчёт.
