### ISSUE TITLE
Unexpected Character {

### ISSUE THREAD

**Issue by Vashiru** [kosmodrey/telebot#23]
When I launch my script that requires Telebot I keep getting:

```
/node_modules/telebot/lib/telebot.js:86
      let { url, cert } = this.webhook;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/renevlugt/Development/albys_bot/index.js:4:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

**Comment by kosmodrey** [comment]
Hi. TeleBot requires Node.js version 6.0 and beyond. Please check your version.

**Comment by Vashiru** [comment]
Updated to Node 6.5.0:

```
/node_modules/telebot/lib/telebot.js:304
    for (let type of types) {
                   ^

TypeError: types[Symbol.iterator] is not a function
    at TeleBot.on (/Users/renevlugt/Development/albys_bot/node_modules/telebot/lib/telebot.js:304:20)
    at Object.<anonymous> (/Users/renevlugt/Development/albys_bot/index.js:13:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

If I change to ```for(let type in types)``` I get 

```
[bot.info] new methods: keyboard, button, inlineKeyboard, inlineButton, answerList, getMe, sendMessage, forwardMessage, sendPhoto, sendAudio, sendDocument, sendSticker, sendVideo, sendVoice, sendLocation, sendVenue, sendContact, sendChatAction, getUserProfilePhotos, getFile, getChat, leaveChat, getChatAdministrators, getChatMember, getChatMembersCount, kickChatMember, unbanChatMember, answerInlineQuery, answerCallbackQuery, editMessageText, editMessageCaption, editMessageReplyMarkup, setWebhook
[bot.error.webhook] <html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>
```

I tried both the latest release and current develop version. I'm using polling rather than webhooks. Tried both the spelling pooling and polling on both versions.

**Comment by Vashiru** [comment]
Actually turns out that was a mistake in my script, 'text' works fine but the code before it where they type was a regex broke it. Also came to the conclusion that if you enter an incorrect api token it tries to fall back to webhooks and fails. A more graceful way to notify a dev of his mistake might be better.
