### ISSUE TITLE
sendPhoto with notification disabled throws an error

### ISSUE THREAD

**Issue by maddin77** [kosmodrey/telebot#28]
Using `bot.sendPhoto` with the `notify: false` option throws the following error:

```
_http_outgoing.js:456
    throw new TypeError('First argument must be a string or Buffer');
    ^

TypeError: First argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:456:11)
    at Request.write (/tmp/telebot/node_modules/request/request.js:1387:27)
    at FormData.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at FormData.emit (events.js:188:7)
    at FormData.CombinedStream.write (/tmp/telebot/node_modules/combined-stream/lib/combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (/tmp/telebot/node_modules/combined-stream/lib/combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (/tmp/telebot/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/tmp/telebot/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.CombinedStream._getNext (/tmp/telebot/node_modules/combined-stream/lib/combined_stream.js:79:10)
```

I tracked the error down to [methods.js#L289](https://github.com/kosmodrey/telebot/blob/master/lib/methods.js#L289) where `form` gets passed as `data` instead of `form` (according to [telebot.js#L262](https://github.com/kosmodrey/telebot/blob/master/lib/telebot.js#L262)). Changing the line to 

``` js
return this.request(`/${ url }`, form);
```

will result in the request going through and the photo being send like expected, but will make the tests fail so i'm sure that's not the root cause. Unfortunately, i'm not familiar enough with the lib to pinpoint it myself.

To reproduce:

``` js
const TeleBot = require('telebot');
let t = new TeleBot("TOKEN");
t.sendPhoto("CHAT_ID", "https://telegram.org/img/t_logo.png", {
    notify: false
});
```

I'm using node `v6.7.0`, npm `v3.10.8` & telebot `v1.0.6`.

**Comment by kosmodrey** [comment]
Hi, thank you for your report!

For some reason request library don't like booleans in formData 😕
